# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6665c84675666922acd9bb15a27ef1e360bee5e572924d1bcdfeb1ab7d8d904bc65f66cb8f0073d6c3fbef41c732a5193d519ac40853f423766bb15ec1929844

test:
  secret_key_base: 0b1a5c9c0a2a1d97972949a700ec90f182ffd3972b0ff767a5b519edb7c5979dd75c5d19f0bf9c2ebdd58806a2c35487154204eb34bec7d454fe62940a0e88ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
